### ISSUE TITLE
Drive link is not working

### ISSUE THREAD

**Issue by machinelearningzuu** [yogeshry/Plant-disease-classification-Using-leaf-image#1]
Hi there, the provided drive link is not working, can you please check?

**Comment by Sakib2263** [comment]
Sure. I will update the link soon again and let you know.

**Comment by machinelearningzuu** [comment]
Thank you so much for the support.

**Comment by Sakib2263** [comment]
I think you will find the whole dataset from here. It was probably originally shared on Kaggle first.

https://www.kaggle.com/datasets/emmarex/plantdisease
